notifications:
  email: false
language: java
jdk:
- oraclejdk8
install: gradle shadowJar
deploy:
  provider: releases
  api_key:
    secure: FM6wLkN5RI+daeQuTU6BPT9fYT+UAgL0zJuUeutc6Ov8hJzJUWkLTlqsxL/7xqyn+H23+GxjTWELTUrvFkKr22n/2FMcA4uwpx+Fptp6CXC91x3Vy/51EqB7myBfYyIM26+LA8LTn7HZAylO9XvpeUpSUvdTKVQW6k224DmCaLY=
  file: build/distributions/bazi.jar
  on:
    tags: true
    repo: schummar/bazi
after_success:
- gem install travis-custom-deploy
- travis-custom-deploy sftp build/distributions/
env:
  global:
  - secure: POVspFmyNAVZq7w8JyivGjHYylx0LO6FcNjhNXFpPVbRYnG10xU/VPpVaeTbaPKWQjXCn9eOeY7qzzYWtJv394aNfVF9OsA+zc12AIEI5wRqzL0WxfopSTvThgOom0XLhvThsYlWO6+PZQQqtuMHrkfjvwKe8ExTYRap6+TDybU=
  - secure: dyVQOwupMWoddhiIjz6+MsLLlpD6astdw1zVPfsWq/yPiH9bAxb245Q/b7IgX2qarTXwHoKnxxKkaUOxCBxvkf6XZHENx6gTn+EnCEBlgj8RpH6IFOl7Pps9JFCpMem2Z0X0tIITwRveEW3DQl53JQSWNJAbQOMLD2JJsAjDEMU=
  - secure: UobThMeJcBMVfVPdtogWvP4SFLZvZe9Oo8sLL2hNkN6Y4SAceKH1ci3IB/pnx+FVUefwRGVVxAfoDDNglVnEBMJcW2++XmVfZL7kdd3/1sXmF8TgfxhB3f1VKG6dlgz5SnaqLikAtjoQhrKDgSZM3qIfZ8OOG9+37KlasLKTC9U=
  - secure: FDUGH/b/CC1XbDVoqkZ4w87L0qk0oG8NtOga3FPAzshAXBtaQyPm3Ew1BvXPqkaOYDJk0o33j6mpPo/xAdZpGPPAkguqi65gcKeao3OklsoLcQRpJLnCLA1+wX1DkAvR/2SOaXZTVZRKdBUfbQ2pHiFYMFhn9FYbLZNuVtexEaA=
