notifications:
  email: false

language: java
jdk:
  - oraclejdk8

env:
  global:
  - secure: F5/SVRO4FYfAflDwujrzcjZIxqAOR8YUcoF88//pI7NFSHQkBiXKyNh6RrQGrroAg4ppTZfZYicHBDoBK3OjkU9is8TtlnIu2DJAfOsgbaCOv6C4r2VuUr0B2VUr0DzuZKeDPdfWB5XZ1sYoKEGkTM5fU/jVjkUbZh/BEDOAB6E=
  - secure: opK0hpUT/gqOwsi+i/uMnWbXGV7HpWhse4h+oJ7A5S5b/ZfouT3x3r2BTwbTv2T3LnvxSrpJucz92FWrwY28pX0FcoaJm/hH3tDXZN/mo5KnVF2wK2E+WentSoR8Tfz717IywdyqgE6F5cSv3IfkAh3l2C0mkOg5kHU6DDdBiKU=
  - secure: mYt1m88jxlHukA92zY2T2XhzD795dFmKF9iNHga1dIjHeeC9r420KsyFyrvAHeW5LpO3tPR0olFmr96VBRHA8Ot1EqMKjBVM1AoVeW4NGHJDERXIropK3adR21N1Xv2Voq9thHbFEywH/Rn3d1KzqrrRpXqxQbpN3jvHM6/zT4I=
  - secure: F6DQX1d3JuyY8jUi88SRfaKofhkP9MWRUW8rXzhzA6ivRgHvqI1czh/lfMERLXZOemLHVzDp/U9ovHDmxp+d1FxT/YlL1D7mxDLmOHvw4v1Nsl0tfnKJmUrukI8pjgF/MJIYUk2B3wAkl2f99fuNLQ61+eMxlPXQGi16agp5dOA=

install: gradle shadowJar

deploy:
  provider: releases
  api_key:
    secure: FM6wLkN5RI+daeQuTU6BPT9fYT+UAgL0zJuUeutc6Ov8hJzJUWkLTlqsxL/7xqyn+H23+GxjTWELTUrvFkKr22n/2FMcA4uwpx+Fptp6CXC91x3Vy/51EqB7myBfYyIM26+LA8LTn7HZAylO9XvpeUpSUvdTKVQW6k224DmCaLY=
  file: build/distributions/bazi.jar
  on:
    tags: true
    repo: schummar/bazi

after_success:
  - gem install travis-custom-deploy
  - travis-custom-deploy sftp build/distributions/
