notifications:
  email: false
language: java
jdk:
- oraclejdk8
install: gradle shadowJar
deploy:
  provider: releases
  api_key:
    secure: FM6wLkN5RI+daeQuTU6BPT9fYT+UAgL0zJuUeutc6Ov8hJzJUWkLTlqsxL/7xqyn+H23+GxjTWELTUrvFkKr22n/2FMcA4uwpx+Fptp6CXC91x3Vy/51EqB7myBfYyIM26+LA8LTn7HZAylO9XvpeUpSUvdTKVQW6k224DmCaLY=
  file: build/distributions/bazi.jar
  on:
    tags: true
    repo: schummar/bazi
after_success:
- chmod 600 deploy_key
- sftp -i deploy_key -b upload bazi@schummar.de
before_install:
- openssl aes-256-cbc -K $encrypted_35fdb35dd58e_key -iv $encrypted_35fdb35dd58e_iv
  -in deploy_key.enc -out deploy_key -d
env:
  global:
  - secure: Z4Erm11fbuug+HNZ2WIEvpgwiek4rnNX3ZvyBUGsAZJxlg5JZkgxAworofcZAZqHnuuIC04pFbhTf/QvkDHhAlyK3c4xRrOs0XJ1kgqmP1+2ENjjrOwKgKNc62xBeDC/wRNJ8JoCvjt8eO5lDbqKnrnlJngASnVDmJOABZfeb7o=
